package main

import "agentload/internal/snapshot"

func defaultMetricRegistry() []snapshot.MetricRegistryEntry {
	return []snapshot.MetricRegistryEntry{
		{
			Key:          "recent_movement",
			Family:       "workload",
			Label:        "Recent movement",
			Unit:         "sessions",
			Source:       "local transcript or activity-log events",
			Window:       "config.idle_gap_seconds",
			MissingState: "unavailable when no local activity event is available",
			Description:  "Counts sessions with local event movement inside the active window; visible processes alone do not make this non-zero.",
		},
		{
			Key:          "known_sessions",
			Family:       "workload",
			Label:        "Known sessions",
			Unit:         "sessions",
			Source:       "transcripts, command hints, or fallback session ids",
			MissingState: "zero only means no session evidence was observed",
			Description:  "Counts observed AI-agent sessions and role splits; process-only rows are not promoted into sessions.",
		},
		{
			Key:          "process_pressure",
			Family:       "runtime",
			Label:        "Process pressure",
			Unit:         "pids",
			Source:       "visible local AI process rows",
			MissingState: "zero means no visible matching process at sample time",
			Description:  "Counts visible local PIDs separately from recent movement or known sessions.",
		},
		{
			Key:          "process_resources",
			Family:       "runtime",
			Label:        "Process resources",
			Unit:         "cpu/memory/io",
			Source:       "per-PID local process counters",
			MissingState: "unavailable when the operating system counter cannot be read",
			Description:  "CPU, memory, and disk I/O are diagnostic process evidence and must not imply agent activity by themselves.",
		},
		{
			Key:          "system_resources",
			Family:       "system",
			Label:        "System resources",
			Unit:         "cpu/memory/disk/network/thermal pressure",
			Source:       "whole-machine OS counters and public macOS thermal state when available",
			MissingState: "unavailable when system sampling is unsupported; thermal state is separately unavailable when the public API cannot provide it",
			Description:  "Whole-machine pressure is useful context, but it is not attributed to AI agents without process evidence. Thermal pressure is not a temperature or fan-speed reading.",
		},
		{
			Key:          "role_matrix",
			Family:       "lineage",
			Label:        "Agent role matrix",
			Unit:         "sessions",
			Source:       "thread source, parent thread, lane paths, and independent-run evidence",
			MissingState: "unknown role when no reliable role evidence exists",
			Description:  "Main-agent and subagent counts are session-level facts and should not be guessed from process names alone.",
		},
		{
			Key:          "tool_coverage",
			Family:       "coverage",
			Label:        "Tool coverage",
			Unit:         "sessions/pids",
			Source:       "per-tool aggregation of known sessions, recent movement, and process pressure",
			MissingState: "zero only means no session or process evidence was observed for that tool",
			Description:  "Per-tool rows keep known sessions, recent movement, and process pressure as separate rails; process pressure must not be treated as recent movement.",
		},
		{
			Key:          "token_usage",
			Family:       "economics",
			Label:        "Token usage",
			Unit:         "tokens",
			Source:       "parsed local transcript usage fields",
			MissingState: "unavailable when usage fields are absent; never infer zero from process duration",
			Description:  "Token totals are measured only when the local trace contains usage fields.",
		},
		{
			Key:          "output_token_throughput",
			Family:       "workload",
			Label:        "Output token throughput",
			Unit:         "output tokens/second",
			Source:       "positive output-token events and safe cumulative-output deltas from local transcripts",
			Window:       "trailing 300 seconds of wall time",
			MissingState: "unavailable, no_data, and stale remain distinct from a measured zero rate",
			Description:  "Divides output tokens attributed to the trailing wall-time window by 300 seconds; cumulative deltas spanning sparse observations are distributed uniformly across their observed interval. This is workload throughput, not model decode speed.",
		},
		{
			Key:          "runtime_telemetry",
			Family:       "adapter",
			Label:        "Runtime telemetry",
			Source:       "optional future OpenTelemetry or JSONL runtime adapters",
			MissingState: "absent unless an adapter is configured",
			Description:  "Imported runtime telemetry can strengthen evidence but must not replace local process/session truth.",
		},
		{
			Key:          "diagnostic_export",
			Family:       "diagnostics",
			Label:        "Diagnostic export",
			Source:       "sanitized local snapshot",
			MissingState: "available when the local server can produce a sanitized snapshot",
			Description:  "Exports a minimized evidence bundle that omits raw prompts, absolute paths, command arguments, and environment variables.",
		},
	}
}
